apiVersion: v1
kind: Service
metadata:
  name: aks
  namespace: namespace-workflow-1702637253600
spec:
  type: LoadBalancer
  selector:
    app: aks
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000